# Generated by Django 2.2.5 on 2019-09-30 04:25

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xls', models.FileField(upload_to=payroll.models.user_directory_path)),
            ],
        ),
    ]
